name: Deploy Service to App Engine

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: 'Npm Install'
        run: npm install
        working-directory: ./service

      - name: Env Test
        run: echo $API_KEY && node server.js
        working-directory: ./service
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ADMIN_ACCOUNT_KEY: ${{ secrets.ADMIN_ACCOUNT_KEY }}
