name: Deploy Service to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
          project_id: habitsapi-426700

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        working-directory: ./service

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #     project_id: your-gcp-project-id
      #     export_default_credentials: true

      # - name: Deploy to App Engine
      #   run: gcloud app deploy --quiet
      #   working-directory: ./service
