name: Deploy Service to App Engine

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
          project_id: habitsapi-426700

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Env Test
        run: echo $API_KEY && node service.js
        working-directory: ./service
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ADMIN_ACCOUNT_KEY: ${{ secrets.ADMIN_ACCOUNT_KEY }}
